-- AlterTable
ALTER TABLE `Colony` ADD COLUMN `fleetSlots` INTEGER NOT NULL DEFAULT 4;

-- AlterTable
ALTER TABLE `Player` ADD COLUMN `missionState` JSON NULL;

-- AlterTable
ALTER TABLE `Vehicle` ADD COLUMN `activeHours` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `assignment` TEXT NOT NULL DEFAULT '',
    ADD COLUMN `buildDayLabel` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `capacityM3` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `condition` INTEGER NOT NULL DEFAULT 100,
    ADD COLUMN `kindLabel` VARCHAR(191) NOT NULL DEFAULT 'van',
    ADD COLUMN `maintenanceCost` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `statusLabel` VARCHAR(191) NOT NULL DEFAULT 'idle';
