include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    file_names: true

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: ignore
